parameters:
  environment: dev
  azureServiceConnection: WTW-CRBATMO-DEV
  stateResourceGroupName: crbatmo-esp-d-em28-cnfgrp
  stateStorageAccountName: crbatmoesptfst001
  stateStorageContainerName: espappinfratfstate
  stateLocation: francecentral
  ResourceGroupName: crbatmo-esp-d-em28-rgrp
  location: francecentral
  subscriptionName: WTW-CRBATMO-DEV
  applicationId: esp
  rgName: crbatmo-esp-d-em28-rgrp